#_meta.script_name: process-urls
#_meta.script_name: process-papers
#_meta.script_name: process-pdfs
#_meta.script_name: extract-features
#_meta.script_name: share-pdfs
#_meta.script_name: embed-images

#_meta.script_name: onedrive-links

######################

#_meta.script_name: fix-items
#_meta.script_name: link-semantic-scholar
#_meta.script_name: process-attachments
#_meta.script_name: extract-attachment-feature
_meta.script_name: onedrive-links

parents: [secrets, notion]

dry-run: yes

#source-name: pdf

remove-imports: yes

update-existing: yes

paper-types:
  - conferencePaper
  - journalArticle
  - preprint


zotero-storage: C:\Users\anwan\Zotero\storage
zotero-cloud: C:\Users\anwan\OneDrive\Papers\zotero
wordcloud-root: C:\Users\anwan\OneDrive\Papers\wordclouds
onedrive-root: C:\Users\anwan\OneDrive

#wordcloud._type: wordcloud


fixer._type: url-fixer

#feature-processor._type: github-extractor
feature-processor._type: wordcloud

share-type: download
source-name: Wordcloud



