#_meta.script_name: process-urls
#_meta.script_name: process-papers
#_meta.script_name: process-pdfs
#_meta.script_name: extract-features
#_meta.script_name: share-pdfs
#_meta.script_name: embed-images

#_meta.script_name: onedrive-links

######################

#_meta.script_name: fix-items
#_meta.script_name: link-semantic-scholar
#_meta.script_name: process-attachments
#_meta.script_name: extract-attachment-feature
#_meta.script_name: onedrive-links
#_meta.script_name: sync-notion
#_meta.script_name: item-feature

#_meta.script_name: process
#_meta.script_name: sharing
_meta.script_name: publish

#_base: [secrets, notion]
_base: [update]
#_base: [pdfs]

#limit: 1

#silence-config: no
#silence-scripts: no

dry_run: yes

#silent: yes

#extractor._type: url-fixer
#extractor._type: google-scholar
#extractor._type: semantic-scholar

#source-name: pdf

#collection: media

#ignore-brand: yes

#pbar: yes
#silent: yes
#silence-config: yes
#silence-scripts: yes

#remove-imports: yes

#update_existing: yes

#paper_types:
#  - conferencePaper
#  - journalArticle
#  - preprint


#zotero_storage: C:\Users\anwan\Zotero\storage
#zotero_cloud: C:\Users\anwan\OneDrive\Papers\zotero
#wordcloud_root: C:\Users\anwan\OneDrive\Papers\wordclouds
#onedrive_root: C:\Users\anwan\OneDrive

################

#wordcloud._type: wordcloud


#fixer._type: url-fixer

#feature-processor._type: github-extractor
#feature-processor._type: wordcloud

#share-type: download
#source-name: Wordcloud



