################################################################################
# Zotero
zotero._type: zotero
zotero-library-type: user

zotero-library: # MISSING REQUIRED number
zotero-api-key: # MISSING REQUIRED string


################################################################################
# OneDrive
onedrive._type: onedrive-auth
graph-scopes:
  - Files.Read
  - Files.Read.All
  - Files.ReadWrite.All

graph-app-id: # MISSING REQUIRED string
client-secret: # MISSING REQUIRED string


################################################################################
# Notion

notion-secret: # MISSING REQUIRED string
notion-database-id: # MISSING REQUIRED string



################################################################################
# Note: see the Readme for instructions on how to get the necessary secrets and IDs.

