################################################################################
# Zotero
zotero._type: zotero
zotero_library_type: user

zotero_library: # MISSING REQUIRED number
zotero_api_key: # MISSING REQUIRED string


################################################################################
# OneDrive
onedrive._type: onedrive-auth
graph_scopes:
  - Files.Read
  - Files.Read.All
  - Files.ReadWrite.All

graph_app_id: # MISSING REQUIRED string
client_secret: # MISSING REQUIRED string


################################################################################
# Notion

notion_secret: # MISSING REQUIRED string
notion_database_id: # MISSING REQUIRED string



################################################################################
# Note: see the Readme for instructions on how to get the necessary secrets and IDs.

