
# fig process update
# fig sharing update
# fig publish update

_base: [secrets, notion]


#source-name: pdf

#ignore-brand: yes

#silent: yes

onedrive-limit: 15

pbar: yes
silence-config: yes
silence-scripts: yes

remove-imports: yes

skip_if_missing: yes

#update_existing: yes

#zotero-query:
#  tags: [omnicite:features:]

paper_types:
  - conferencePaper
  - journalArticle
  - preprint

#attachment-base-root: C:\Users\anwan\OneDrive\
#zotero_storage: C:\Users\anwan\Zotero\storage
#zotero-cloud: C:\Users\anwan\OneDrive\Papers\zotero
#wordcloud-root: C:\Users\anwan\OneDrive\Papers\wordclouds
#onedrive-root: C:\Users\anwan\OneDrive


